-- Run this script in the Supabase SQL Editor to create the required table

CREATE TABLE IF NOT EXISTS analysis_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_url TEXT,
    total_comments INTEGER,
    positive_pct REAL,
    negative_pct REAL,
    neutral_pct REAL,
    peak_timestamp TEXT,
    ai_summary TEXT,
    video_title TEXT,
    channel_name TEXT,
    analyzed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable RLS (Row Level Security) so the API can read/write freely,
-- or create RLS policies if desired.
ALTER TABLE analysis_history DISABLE ROW LEVEL SECURITY;
